### ISSUE TITLE
リクエストパラメータなしでGETが呼べない

### ISSUE THREAD

**Issue by hhiroshell** [cndjp/qicoo-api#17]
以下の用に呼ぶとエラーになっちゃうみたいです。

    curl -X GET 'http://localhost:8080/v1/jkd1812/questions

リファレンスによるとデフォルト値があるので、これでも動くことを期待してしまう。

**Comment by Sugi275** [comment]
すいません、パラメータ指定は必須でお願いしたいです。
goのmuxの仕様上　パラメータの省略はかなり厳しいことがわかりました。
api-referenceにDefaultを書きましたが、パラメータ指定を必ず頂けると幸いです

```
curl -X GET 'http://localhost:8080/v1/jkd1812/questions?start=1&end=10&sort=created_at&order=desc'
```
