### ISSUE TITLE
ヘルスチェックのAPIがあるとうれしい

### ISSUE THREAD

**Issue by hhiroshell** [cndjp/qicoo-api#18]
Manifestを書いていいて、Readiness/Liveness Probeから呼ぶのにちょうどいいAPIがないなーと思いましてた。
優先度低め。これまた時間があったらPRします。

**Comment by Sugi275** [comment]
qicoo-api に Readiness/Liveness Probe で利用可能なREST APTを追加しました。PRに含まれている内容なので、ReviewののちにMasterへマージします。

**Comment by translucens** [comment]
#16 で追加済
