### ISSUE TITLE
CORS対応が必要

### ISSUE THREAD

**Issue by translucens** [cndjp/qicoo-api#19]
いいねのAPIコールでは、HTMLから見ると別のオリジン宛にPUTを送信するのでCORS対応が必要。
`OPTIONS` リクエストが事前に来るので、規定のヘッダを付けて返す必要がある。https://developer.mozilla.org/ja/docs/Web/HTTP/HTTP_access_control#Preflighted_requests

**Comment by Sugi275** [comment]
goでCORSが出来るように調べてみます。Questionの取得や登録は、CORS対応の対象ではないのです？

**Comment by translucens** [comment]
* 取得 - GET - フロントが特殊なヘッダを足さなければOK
* 登録 - POST - `Content-Type`に制限があって、`application/json`で受け付けるなら必要ですね

**Comment by translucens** [comment]
#20 で追加した
