### ISSUE TITLE
qicoo-api/src/handler/question-create_test.go について

### ISSUE THREAD

**Issue by nnao45** [cndjp/qicoo-api#3]
もう考えているかもですが、`CreateQuestionRedis`関数のtestをするなら、一回mockでMySQL（ORマッピングもして）とRedisを立てて、そいつらに実際にクエスションを作って、読み込んでその内容が事前に用意した文字列と一致するかのテストの方がテストの信頼性が高いです。
今のままだと、ただ単にライブラリに適当な値突っ込んでもerror型が帰ってこないってテストなので。

・・・お気づきカモですが、僕も作ろうか悩んで、「一回mockでMySQL（ORマッピングもして）とRedisを立てて、そいつらに実際にクエスションを作って、読み込んでその内容が事前に用意した文字列と一致する」を確認するのがクソめんどくさかったらやりませんでした笑

**Comment by nnao45** [comment]
まぁ、妥協案でQuestion型をモックのMySQLのORMに一行突っ込んだあとに、普通にSELECT文で引っ張って照合するってのもありかと思われます。

**Comment by Sugi275** [comment]
Issues ありがとうございます。

色々悩んだのですが、go test 時には、Redis・MySQLをMockとして一時的に立てて Createなどの実装にたいしてテストを行おうと考えています (Travis, Local共に)

1. Travis時は、TravisCI上のRedis・MySQLを利用
2. Local時は、go実行環境のRedis・MySQL (Docker) を利用

下記のbranch上に、QuestionListをDocker利用してtestを実行している内容を実装しています。
Makefile上でdocker run と docker kill を記載する形です。
https://github.com/cndjp/qicoo-api/blob/sugimount/test-refact/Makefile#L57-L69

上記のテストであれば、Redis・MySQLを利用して実際にデータを登録・削除を行い確認が出来るので、良いのかなと思っています。

**Comment by nnao45** [comment]
dockerはdockerでメリデメがあるとは思いますが、
モックライブラリよりdockerがいい理由とかありますか？

**Comment by nnao45** [comment]
手元で動かす時に割とオーバーヘッドが大きそうですし、
現状モックテストは一応動いているのであえて潰して新しくテストを構築するのはちょっとどうなんでしょって思いました。

**Comment by Sugi275** [comment]
MySQLはエヌナオさんが使用していたライブラリで良いと思うのですが、Redis用にデータの出し入れを実行できるライブラリが無かったように思えたので、Dockerを採用しました。

■MySQLを実際に稼働するライブラリ
"github.com/lestrrat-go/test-mysqld"

**Comment by nnao45** [comment]
> Redis用にデータの出し入れを実行できるライブラリ

redigomockじゃダメですか？

**Comment by nnao45** [comment]
listの方のテストは実際にモックのredisに突っ込んで照合しているという認識ですが、実はそれは俺の妄想だった的な感じでした？w

**Comment by Sugi275** [comment]
あれ、エヌナオさんの指摘で、Redigomockだと実際にデータを書き込んでいるわけではないので、信頼性が無いよね～という意味で理解してしまっていました。
Redigomockはあくまでも、想定される結果を記載しているので、実際に書き込んでいないのではという。

下記のコードの例では、redigomockとして "OK" を単純に返しているだけなので、実際にRedis建てた方がいいんじゃないという指摘だと思ってました。

https://github.com/cndjp/qicoo-api/blob/master/src/handler/question-create_test.go#L41-L44

**Comment by nnao45** [comment]
ありゃっwwwっww

**Comment by nnao45** [comment]
↑に書いたようにCreateQuestionRedis関数の話ですね、それ。
listのtestの方は、実際にZADDで値を突っ込んでいて、最後commentフィールドが"I am mock"かどうか見ています。

```
if _, err := internalTestRedisConn.Do("HSET", "questions_"+mockChannel, 1, mockQuestionJS); err != nil {
		t.Error(err)
	}

	//SortedSet(Like)
	if _, err := internalTestRedisConn.Do("ZADD", "questions_"+mockChannel+"_like", mockQuestion.Like, mockQuestion.ID); err != nil {
		t.Error(err)
	}

	//SortedSet(CreatedAt)
	if _, err := internalTestRedisConn.Do("ZADD", "questions_"+mockChannel+"_created", mockQuestion.CreatedAt.Unix(), mockQuestion.ID); err != nil {
		t.Error(err)
	}```

**Comment by nnao45** [comment]
create側も、

```
err := handler.CreateQuestionRedis(mockPool, mockQuestion)```

で作ったquestionのredisから、ZRANGEとかでひっぱってきて、commentフィールドが"I am mock"かどうか見れれば、関数の正当性を確認できるかと。

**Comment by nnao45** [comment]
流れとしてはmockのMySQLとRedisを立ち上げて、

```
CreateQuestionDB(m *gorp.DbMap, question Question)
```
と
```
err := handler.CreateQuestionRedis(mockPool, mockQuestion)
```
にmockのコネクション型で生成して、commentフィールドが"I am mock"かどうか見る感じですかね、大変ですけど。

**Comment by Sugi275** [comment]
うーん。実際にRedisとMySQLを建てる方式の方が、楽そうな気がしています。
現段階で、DockerのRedisとMySQLにテストデータを入れる部分は実装出来ているので、Createのテストも楽々出来る状態だったりします。

(TravisのテストとLocalのテストコードを共通出来るうれしさもある)

DockerでMockを建てる方式が良いなあと思っていますが、いかがでしょう？

**Comment by nnao45** [comment]
「dockerを立ち上げて」というワンクッションある時点でコードのテストとは言えなさそうですけど、どうでしょ？

**Comment by nnao45** [comment]
もうそれだとモックテストというよりかはシナリオテストだったりします（そのテストが成立するためにはサービスが上がってないといけない）。

**Comment by nnao45** [comment]
そしたら、もうgo testなんかやんないで、素直にモノホンのコードをテスト環境で走らせて終わりでいい気がします。

**Comment by Sugi275** [comment]
うーんそうですねえ・・・。現時点でもMySQLのMock "github.com/lestrrat-go/test-mysqld" は、MySQLをinstallしておく必要がある縛りがあるので、「DockerでMySQLを起動する」と「"github.com/lestrrat-go/test-mysqld"」は、実際は同じことをやっている理解でいます。

Dockerを使用することでtestの前提条件が、「MySQLをinstallしておくこと」から「Dockerをinstallしておくこと」に変わりますが、どちらにせよinstallをしておかないといけないので、ポータビリティは変わらないという理解です。

というMySQLの実装を考えると、Redisも同様に考えて実際にDockerで起動するのはコストは変わらないと思っています。(MySQLは実際に起動しているので、RedisだけMockにこだわる必要はない)



とここまで書いて気が付きましたが、私はシナリオテストをやりたいんだと思います。
一般的なテストコードって、作成するfunctionごとに様々な値をテストして問題ないことを確認して行くんだと思うんですけど、今回 qicoo-api ではそこまでやるのはちょっと辛いなと思っています。
function 一個一個実行するよりも、シナリオテストをPASSすることを確認することで、ある程度の品質を担保したいなあという方針で考えていました。

**Comment by nnao45** [comment]
シナリオテストで進めましょう。クローズ。
